#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-58
#SBATCH -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1  # We're launching 1 node with 1 Nvidia T4 GPUs each
#SBATCH -t 0-24:00:00

time apptainer exec container.sif python main.py alvis \
	--data_path "/cephyr/users/audinet/Alvis/llm-distillator/data/dredze_amazon_reviews.txt" \
	--out_dir "/cephyr/users/audinet/Alvis/llm-distillator/results/" \
	# --num_samples 20 \
	--batch_size 4
