#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-58
#SBATCH -p alvis
#SBATCH -N 1 --gpus-per-node=T4:1  # We're launching 1 node with 1 Nvidia T4 GPUs each
#SBATCH -t 0-24:00:00

time apptainer exec container.sif python classify_bert.py
